-- MySQL Script generated by MySQL Workbench
-- Sat Mar 25 20:10:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restaurant_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurant_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurant_management` DEFAULT CHARACTER SET utf8 ;
USE `Restaurant_management` ;

-- -----------------------------------------------------
-- Table `Restaurant_management`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`staff` (
  `idstaff` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `apparatus_employed` DATE NOT NULL,
  `dismissal_from_work` DATE NOT NULL,
  PRIMARY KEY (`idstaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`recipes` (
  `idrecipes` INT NOT NULL AUTO_INCREMENT,
  `information` TEXT NOT NULL,
  `instruction` TEXT NOT NULL,
  `photo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idrecipes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`menu(dishes)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`menu(dishes)` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cost` DOUBLE NOT NULL,
  PRIMARY KEY (`idmenu`),
  INDEX `recipe_id_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `recipe_id`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `Restaurant_management`.`recipes` (`idrecipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`tables` (
  `idtables` INT NOT NULL AUTO_INCREMENT,
  `seats` INT NOT NULL,
  PRIMARY KEY (`idtables`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `information` TEXT NOT NULL,
  `total_cost` DOUBLE NOT NULL,
  `table_id` INT NOT NULL,
  PRIMARY KEY (`idorders`),
  INDEX `table_id_idx` (`table_id` ASC) VISIBLE,
  CONSTRAINT `table_id`
    FOREIGN KEY (`table_id`)
    REFERENCES `Restaurant_management`.`tables` (`idtables`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`table_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`table_reservation` (
  `idtable_reservation` INT NOT NULL AUTO_INCREMENT,
  `reservation_time` DATETIME NOT NULL,
  `table_id` INT NOT NULL,
  PRIMARY KEY (`idtable_reservation`),
  INDEX `table_id_idx` (`table_id` ASC) VISIBLE,
  CONSTRAINT `table_id`
    FOREIGN KEY (`table_id`)
    REFERENCES `Restaurant_management`.`tables` (`idtables`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`statistics` (
  `idstatistics` INT NOT NULL AUTO_INCREMENT,
  `information` TEXT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idstatistics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`work_management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`work_management` (
  `idwork_management` INT NOT NULL AUTO_INCREMENT,
  `work_ time` VARCHAR(255) NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`idwork_management`),
  INDEX `staff_id_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Restaurant_management`.`staff` (`idstaff`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant_management`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_management`.`accounts` (
  `idaccounts` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`idaccounts`),
  INDEX `staff_id_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Restaurant_management`.`staff` (`idstaff`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
